print('new world')
print('newer world')
print('here I try to understand what is going on!!!')
print("so ok I'm starting getting this... I think")
print("something still not clear")
print('what exactly is not clear?')